name: dotnet-test
on:
    pull_request:
        types:
            - opened
            - synchronize
        paths:
            - 'src/**'
            - 'tests/**'
    push:
        branches:
            - main
        paths:
            - 'src/**'
            - 'tests/**'
    workflow_dispatch: {}
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    test:
        runs-on: windows-latest
        strategy:
            matrix:
                include:
                    - dotnet-version: '5.0.x'
                      framework: 'net5.0'
                    - dotnet-version: '6.0.x'
                      framework: 'net6.0'
                    - dotnet-version: '7.0.x'
                      framework: 'net7.0'
                    - dotnet-version: '10.0.x'
                      framework: 'net10.0'
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - uses: actions/setup-dotnet@v5
              with:
                  dotnet-version: ${{ matrix.dotnet-version }}
            - run: dotnet restore ./tests/Localization.Tests
            - run: dotnet build ./tests/Localization.Tests --configuration Release --no-restore
            - run: dotnet test ./tests/Localization.Tests --configuration Release --no-build --verbosity normal --collect:"XPlat Code Coverage" --framework ${{ matrix.framework }}
            - name: Find coverage output path
              if: matrix.framework == 'net10.0'
              shell: pwsh
              run: |
                  $files = Get-ChildItem -Path . -Filter "coverage.cobertura.xml" -Recurse -File
                  foreach ($file in $files) {
                      Copy-Item -Path $file.FullName -Destination . -Force
                  }
            - name: Run ReportGenerator
              if: matrix.framework == 'net10.0'
              shell: pwsh
              run: |
                  dotnet tool install -g dotnet-reportgenerator-globaltool
                  reportgenerator -reports:"coverage.cobertura.xml" -targetdir:"report" -reporttypes:"Html;MarkdownSummary"
                  Get-Content report/Summary.md | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Encoding utf8
            - uses: actions/upload-artifact@v4
              if: matrix.framework == 'net10.0'
              with:
                  name: coverage-report-${{ matrix.framework }}
                  path: report/
